basic:
  name      : poiseuille
  author    : Sylvain
  date      : 2025-12-15
  dimension : 2
  arch      : cpu
  type      : configuration 

module : 
  flow : true
  chemistry : false
  temperature : false
  porous_media : false
  radiation : false


spaceControl:
  geometry : [0.1,0.1]
  DX : 1e-3


timeControl:
  startTime : 0
  endTime : 10
  DT : 1e-3

flowProperties:
  viscosity : 
    type : constant
    value : 0.01

chemicalProperties:
  source : cantera

boundaryCondition:
  left:
    flow:
      type: inlet
      velocity : [0.01,0,0]
      rho : 1
  right:
    flow:
      type: outlet
      rho: 1
  down:
    flow:
      type: wall
  up:
    flow:
      type : wall
  
initialCondition:
  flow:
    rho : 1
    velocity : [0,0,0]
  

outputControl:
  vtk:
    interval : 0.1
    path : vtk
    LOD : 1
    clear : true
  log:
    interval : 0.1
    LOD : 1
  snapshot:
    interval : 100
    path : snapshot.yaml