basic:
  name      : pyrolysis_test
  author    : Sylvain
  date      : 2025-12-27
  dimension : 2 # 2 or 3
  arch      : cpu # cpu/gpu/vulkan/cuda .etc the platform
  type      : configuration # configuration / snapshot(saved)

module : 
  flow : true
  porous_media : true
  temperature : true
  chemistry : false
  radiation : false

flowProperties:
  viscosity : 
    type : constant # constant/sutherland/mixture
    # # if constant
    value : 2e-5
    # if sutherland
    # As : 1.6e-6
    # Ts : 170
    # # if mixture

thermalPropertiesFluid : 
  normalize:
    Trange : [300,500] # [a,b] means [0,1] will be mapped to [0,1]
  thermalDiff :
    type : derived # constant/Prandtl/derived
    # if constant
    # value : 1e-5
    # # if Prandtl
    Pr : 0.71
    # # if derived
  conductivity: 
    type: polynomial # constant/polynomial/mixture
    # if constant
    # value : 0.01
    # # if polynomial
    data : [0.01,-1e-6,0,0,0] # max 5 order
    # # if mixture
  capacity : 
    type : NASA7 # constant/polynomial/NASA7/mixture
    # if constant
    # value : 10000.0
    # # if polynomial
    # data : [24.78245636, -24.99673416e-03, 80.84730201e-06, -80.68129509e-09, 24.24372837e-12]
    # # if NASA7
    Trange : [200.0, 1000.0, 3500.0]
    data : 
    - [3.78245636, -2.99673416e-03, 9.84730201e-06, -9.68129509e-09, 3.24372837e-12,
      -1063.94356, 3.65767573]
    - [3.28253784, 1.48308754e-03, -7.57966669e-07, 2.09470555e-10, -2.16717794e-14,
      -1088.45772, 5.45323129]
  # if mixture

thermalPropertiesSolid : 
  normalize:
   Trange: [300,500]
  thermalDiff :
    type : derived # constant/derived
    # # if constant
    # value : 1e-5
    # # if derived
  conductivity: 
    type: polynomial # constant/polynomial/mixture
    # if constant
    # value : 4
    # if polynomial
    data : [4,1e-4,0,0,0] # max 5 order
    # # if mixture
  capacity : 
    type : NASA7 # constant/polynomial/NASA7/mixture
    # # if constant
    # value : 1000
    # # if polynomial
    # data : [1000,1,-1e6,0,0]
    # # if NASA7
    Trange : [200.0, 1000.0, 3500.0]
    data : 
    - [3.78245636, -2.99673416e-03, 9.84730201e-06, -9.68129509e-09, 3.24372837e-12,
      -1063.94356, 3.65767573]
    - [3.28253784, 1.48308754e-03, -7.57966669e-07, 2.09470555e-10, -2.16717794e-14,
      -1088.45772, 5.45323129]
    # if mixture


chemicalProperties:
  type : cantera # cantera/input
  # # if cantera
  # path : YOUR_CANTERA_FILE.yaml
  # if input
  species :
    N2 : 
      state : fluid
      viscosity : 
        type : constant # constant/sutherland
        # # if constant
        value : 1e-5
        # # if sutherland
        # As : 1
        # Ts : 1
      thermodynamic :
        type : constant # constant/NASA7
        # if constant
        enthalpy : 100
        capacity : 1000
        # # if NASA7
        # Trange : [0,0,0]
        # data : [[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]]
      diffusitivity:
        type : constant # constant/Schmidt
        # if constant
        value : 1e-5
        # # if Schmidt
        # Sc : 1.0
      conductivity : 
        type: constant # constant/Prandtl/polynomial
    wood(S) :
      state : solid # solid phase has only thermodynamic properties
      thermodynamic :
        type : constant # constant/NASA7
        # if constant
        enthalpy : 100
        capacity : 1000
        # # if NASA7
        # Trange : [0,0,0]
        # data : [[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]]
    # reaction:



geometry:
  zone1:
    type : sphere # sphere/cylinder/box/cone/stl
    center : [0.05,0.05,0]
    radius : 0.01
  # zone2 :
  #   type : cylinder
  #   center : [0.05,0.05,0]
  #   radius : 0.01
  #   height : 0.01
  #   axis : [0,0,1]
  # zone3 :
  #   type : box
  #   center : [0.3,0.05,0]
  #   size : [0.02,0.01,0.01]
  # zone4 : 
  #   type : cone
  #   center : [0.4,0.05,0]
  #   height : 0.1
  #   radius : 0.02
  #   axis : [0,0.5,0.5]
  # zone5:
  #   type : stl
  #   path : YOUR_STL.stl
  #   scale : 1
  #   translate : [0.6,0.05,0]
  #   rotate : [0,0,0]

initialCondition:
  solid: # to specify the solid area (operation in order)
    solid1:
      zone : zone1 # the zones concerned
      type : poro # concrete/poro/substract
      rho : 400
      # if concrete
      # if substract
      # if poro
      porosity : 0.4
      #   porosity : 0.4
      porousModel : darcy # darcy/darcyforchheimer/ergun
      #   # if darcy
      darcy : 2.5e11
      # # if darcyforchheimer
      # darcy : 2.5e10
      # forchheimer : 6e4
      # if ergun    # solid2:
      exchangeSurface : 1000
      exchangeCoef : 1
    #   zone : zone2
    #   type : poro
    #   rho : 400
    #   porosity : 0.4
    #   porousModel : darcy # darcy/darcyforchheimer/ergun
    #   # if darcy
    #   darcy : 2.5e11
      # # if darcyforchheimer
      # darcy : 2.5e10
      # forchheimer : 6e4
      # if ergun
  flow: # initial condition of flow
    rho : 1
    velocity : [0,0,0] # initial velocity of non-solid volume (to avoid numerical instablity)
  thermal: # initial condition of temperature
    T : 200
    # TS : 500
    # TF : 300
  chemical:
    N2 : 
      zone : ALL
      value : 1
    wood(S):
      zone : zone1
      vaue : 400

boundaryCondition:
  left:
    flow:
      type: inlet
      velocity : [0.01,0,0]
    thermalFluid:
      type: fixedValue # periodic/fixedValue/zeroGradient
      # if fixedValue
      value : 400
      # # if zeroGradient
    thermalSolid : 
      type : none # if the solid area doesn't contact with this boundary, the boundary condition will not be used
    chemical:
      type: fixedValue
  right:
    flow:
      type: outlet
      rho: 1
    thermalFluid:
      type: zeroGradient # periodic/fixedValue/zeroGradient 
      value : 400
    thermalSolid : 
      type : none # if the solid area doesn't contact with this boundary, the boundary condition will not be used
    chemical:
      type: fixedValue
  down:
    flow:
      type: wall
      # velocity : [0,0,0]
    thermalFluid:
      type: fixedValue # periodic/fixedValue/zeroGradient 
      value : 400
    thermalSolid : 
      type : none # if the solid area doesn't contact with this boundary, the boundary condition will not be used
    chemical:
      type: fixedValue
  up:
    flow:
      type : wall
    thermalFluid:
      type: fixedValue # periodic/fixedValue/zeroGradient 
      value : 400
    thermalSolid : 
      type : none # if the solid area doesn't contact with this boundary, the boundary condition will not be used
    chemical:
      type: fixedValue
  
  
spaceControl:
  geometry : [0.1,0.1]
  DX : 1e-3

timeControl:
  startTime : 0
  endTime : 1000
  DT : 1e-3

outputControl:
  vtk:
    interval : 1 # the interval of vtk output
    path : vtk # the relative path of the output folder
    LOD : 1
    clear : false # true to clear all the existing output in the folder
  log:
    interval : 1
    LOD : 1 # 
  snapshot: # resume from the snapshot
    interval : 100 # the interval of snapshot
    path : snapshot # the relative path of the snapshot folder