basic:
  name      : YOUR_CASE_NAME
  author    : YOUR_NAME
  date      : 1970-01-01
  dimension : 2 # 2 or 3
  arch      : cpu # cpu/gpu/vulkan/cuda .etc the platform
  type      : configuration # configuration / snapshot(saved)

module : 
  flow : true
  temperature : false
  porous_media : false
  chemistry : false
  radiation : false

flowProperties:
  eos: weakly_compressible
  viscosity : 
    type : constant # constant/sutherland/mixture
    # if constant
    value : 0.002
    # # if sutherland
    # As : 1
    # Ts : 1
    # # if mixture

thermalPropertiesFluid : 
  conductivity: 
    type: constant # constant/Prandtl/polynomial/mixture
    # if constant
    value : 1000
    # # if Prandtl
    # Pr : 0.71
    # # if polynomial
    # data : [0,0,0,0] # max 4 order
    # # if mixture
  capacity : 
    type : constant # constant/polynomial/NASA7/mixture
    # if constant
    value : 2000
    # # if polynomial
    # data : [0,0,0,0,0]
    # # if NASA7
    # Trange : [0,0,0]
    # data : [[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]]
  # if mixture

thermalPropertiesSolid : 
  conductivity: 
    type: constant # constant/polynomial/mixture
    # if constant
    value : 1000
    # # if Prandtl
    # Pr : 0.71
    # # if polynomial
    # data : [0,0,0,0] # max 4 order
    # # if mixture
  capacity : 
    type : constant # constant/polynomial/NASA7/mixture
    # if constant
    value : 2000
    # # if polynomial
    # data : [0,0,0,0,0]
    # # if NASA7
    # Trange : [0,0,0]
    # data : [[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]]
  # if mixture


chemicalProperties:
  type : cantera # cantera/input
  # # if cantera
  # path : YOUR_CANTERA_FILE.yaml
  # if input
  species :
    N2 : 
      state : fluid
      viscosity : 
        type : constant # constant/sutherland
        # if constant
        value : 1e-4
        # # if sutherland
        # As : 1
        # Ts : 1
      thermodynamic :
        type : constant # constant/NASA7
        # if constant
        enthalpy : 100
        capacity : 1000
        # # if NASA7
        # Trange : [0,0,0]
        # data : [[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]]
      diffusitivity:
        type : constant # constant/Schmidt
        # if constant
        value : 1e-5
        # # if Schmidt
        # Sc : 1.0
      conductivity : 
        type: constant # constant/Prandtl/polynomial
    wood(S) :
      state : solid # solid phase has only thermodynamic properties
      thermodynamic :
        type : constant # constant/NASA7
        # if constant
        enthalpy : 100
        capacity : 1000
        # # if NASA7
        # Trange : [0,0,0]
        # data : [[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]]
    # reaction:



geometry:
  zone1:
    type : sphere # sphere/cylinder/box/cone/stl
    center : [0.1,0.05,0]
    radius : 0.01
  zone2 :
    type : cylinder
    center : [0.2,0.05,0]
    radius : 0.02
    height : 0.01
    axis : [0,1,0]
  zone3 :
    type : box
    center : [0.3,0.05,0]
    size : [0.02,0.01,0.01]
  zone4 : 
    type : cone
    center : [0.4,0.05,0]
    height : 0.1
    radius : 0.02
    axis : [0,0.5,0.5]
  zone5:
    type : stl
    path : YOUR_STL.stl
    scale : 1
    translate : [0.6,0.05,0]
    rotate : [0,0,0]

initialCondition:
  solid: # to specify the solid area (operation in order)
    solid1:
      zone : zone1 # the zones concerned
      type : concrete # concrete/poro/substract
      # if concrete
      # if substract
      # # if poro
      # porosity : 0.4
    # solid2:
    #   zone : zone2
    #   type : substract
  flow: # initial condition of flow
    rho : 1
    velocity : [0,0,0] # initial velocity of non-solid volume (to avoid numerical instablity)
  thermal: # initial condition of temperature
    T : 300
    # TS : 500
    # TF : 300
  chemical:
    N2 : 
      zone : ALL
      value : 1
    wood(S):
      zone : zone1
      vaue : 400

boundaryCondition:
  left:
    flow:
      type: inlet
      velocity : [0.01,0,0]
    thermalFluid:
      type: fixedValue # periodic/fixedValue/zeroGradient
      # if fixedValue
      value : 100
      # # if zeroGradient
    thermalSolid : 
      type : none # if the solid area doesn't contact with this boundary, the boundary condition will not be used
    chemical:
      type: fixedValue
  right:
    flow:
      type: outlet
      rho: 1
    thermalFluid:
      type: fixedValue # periodic/fixedValue/zeroGradient 
      value : 
    thermalSolid : 
      type : none # if the solid area doesn't contact with this boundary, the boundary condition will not be used
    chemical:
      type: fixedValue
  down:
    flow:
      type: wall
    thermalFluid:
      type: fixedValue # periodic/fixedValue/zeroGradient 
      value : 
    thermalSolid : 
      type : none # if the solid area doesn't contact with this boundary, the boundary condition will not be used
    chemical:
      type: fixedValue
  up:
    flow:
      type : wall
    thermalFluid:
      type: fixedValue # periodic/fixedValue/zeroGradient 
      value : 
    thermalSolid : 
      type : none # if the solid area doesn't contact with this boundary, the boundary condition will not be used
    chemical:
      type: fixedValue
  
  
spaceControl:
  geometry : [1,0.1]
  DX : 1e-3

timeControl:
  startTime : 0
  endTime : 1000
  DT : 1e-3

outputControl:
  vtk:
    interval : 1 # the interval of vtk output
    path : vtk # the relative path of the output folder
    LOD : 1
    clear : false # true to clear all the existing output in the folder
  log:
    interval : 1
    LOD : 1 # 
  snapshot: # resume from the snapshot
    interval : 100 # the interval of snapshot
    path : snapshot # the relative path of the snapshot folder