basic:
  name      : cylinder
  author    : Sylvain
  date      : 2025-12-22
  dimension : 2
  arch      : cpu
  type      : configuration # configuration / snapshot

module : 
  flow : true


spaceControl:
  geometry : [1,0.1]
  DX : 2e-4


timeControl:
  startTime : 0
  endTime : 1000
  DT : 2e-4

flowProperties:
  viscosity :
    type: constant
    value: 1e-5

chemicalProperties:
  source : cantera

geometry:
  zone1:
    type : sphere
    center : [0.1,0.05,0]
    radius : 0.01

initialCondition:
  solid:
    solid1:
      zone : ALL
      type : concrete
  flow:
    rho : 1
    velocity : [0,0,0]
  thermal:
    T : 300
  chemical:
    N2 : 
      zone : all
      value : 1
    wood(S):
      zone : zone1
      value : 400

boundaryCondition:
  left:
    flow:
      type: inlet
      velocity : [0.01,0,0]
    thermal:
      type:
    chemical:
      type:
  right:
    flow:
      type: outlet
      rho: 1
    thermal:
      type:
    chemical:
      type:
  down:
    flow:
      type: wall
    thermal:
      type:
    chemical:
      type:
  up:
    flow:
      type : wall
    thermal:
      type:
    chemical:
      type:
  

outputControl:
  vtk:
    interval : 10
    path : vtk
    LOD : 1
    clear : true
  log:
    interval : 1
    LOD : 1
  snapshot:
    interval : 100
    path : snapshot