basic:
  name      : cylinder_poro
  author    : Sylvain
  date      : 2025-12-19
  dimension : 2
  arch      : cpu
  type      : configuration 

module : 
  flow : true
  chemistry : false
  temperature : false
  porous_media : true
  radiation : false


spaceControl:
  geometry : [0.3,0.1]
  DX : 1e-3


timeControl:
  startTime : 0
  endTime : 1000
  DT : 1e-3

flowProperties:
  viscosity : 
    type: constant
    value: 1e-5

chemicalProperties:
  source : cantera

geometry:
  zone1:
    type : sphere
    center : [0.1,0.05]
    radius : 0.01
  # zone2:
  #   type : rectangle
  #   point1 : [0.04,0.02]
  #   point2 : [0.06,0.08]

initialCondition:
  solid:
    solid1:
      zone : [zone1] # 区域 可不加[] 
      type : poro # 类型 poro/concrete
      porosity : 0.6 # 孔隙率 type==poro时访问
      model : Darcy # ergun/darcy/darcyforchheimer
      darcy : 2.5e10 # 达西系数 type==poro model==darcy/darcyforchheimer时访问
      forchheimer : 0.0 # Forchheimer系数 type==poro model==darcy/darcyforchheimer时访问
      

  flow:
    rho : 1
    velocity : [0,0,0]
  thermal:
    T : 300
  chemical:
    N2 : 
      zone : all
      value : 1
    wood(S):
      zone : zone1
      vaue : 400

boundaryCondition:
  left:
    flow:
      type: inlet
      velocity : [0.01,0,0]
    thermal:
      type:
    chemical:
      type:
  right:
    flow:
      type: outlet
      rho: 1
    thermal:
      type:
    chemical:
      type:
  down:
    flow:
      type: wall
    thermal:
      type:
    chemical:
      type:
  up:
    flow:
      type : wall
    thermal:
      type:
    chemical:
      type:
  

outputControl:
  vtk:
    interval : 10
    path : vtk
    LOD : 1
    clear : true
  log:
    interval : 1
    LOD : 1
  snapshot:
    interval : 100
    path : snapshot