basic:
  name      : porous_flow_quick
  author    : benchmark
  date      : 2026-05-11
  dimension : 2
  arch      : cpu
  type      : configuration
  collisionModel : BGK

module : 
  flow : true
  chemistry : false
  temperature : false
  porous_media : true
  radiation : false

flowProperties:
  eos: weakly_compressible
  viscosity : 
    type : constant
    value : 0.002

porousProperties:
  type : darcy
  source : u-darcy
  porosity :
    type : constant
    value : 0.5
  permeability :
    type : constant
    value : 1e-6

spaceControl:
  geometry : [0.2, 0.05]
  DX : 5e-3

timeControl:
  startTime : 0
  endTime : 1.0
  DT : 1e-3

region:
  zone1:
    type : rectangle
    center : [0.1, 0.025]
    width : 0.04
    height : 0.03
  zone2:
    type : rectangle
    center : [0.1, 0.025]
    width : 0.02
    height : 0.01

properties:
  fluid:
    zone : zone1
    flow:
      type : porous
    thermal:
      type:
    chemical:
      type:
  solid:
    solid1:
      zone : zone2
      type : concrete

boundaryCondition:
  left:
    flow:
      type: inlet
      velocity : [0.005, 0, 0]
  right:
    flow:
      type: outlet
      rho: 1
  down:
    flow:
      type: wall
  up:
    flow:
      type: wall

initialCondition:
  flow:
    rho : 1
    velocity : [0, 0, 0]

outputControl:
  vtk:
    interval : 0.1
    path : vtk
    LOD : 1
    clear : true
  log:
    interval : 0.01
    LOD : 1
  snapshot:
    interval : 100
    path : snapshot
